# These two values are the unique identifiers SonarCloud uses
# to know which project to post results to. They must match
# exactly what SonarCloud shows in Project Information.
sonar.organization=davidtruong87hp
sonar.projectKey=davidtruong87hp_taskflow

# Point SonarCloud at the apps folder where all our source code lives.
# It will recursively scan all three services automatically.
sonar.sources=apps

# Tell SonarCloud these are test files, not source
sonar.tests=apps
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Exclude test files from coverage measurement
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/main.ts,**/*.module.ts

# These folders contain generated or third-party code — not ours.
# Scanning them would pollute our metrics with noise.
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

# When we add tests later, coverage reports will be generated here.
# SonarCloud will pick them up automatically from these paths.
sonar.javascript.lcov.reportPaths=apps/api-gateway/coverage/lcov.info,apps/user-service/coverage/lcov.info,apps/task-service/coverage/lcov.info

sonar.sourceEncoding=UTF-8