apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
type: Opaque
stringData:
  slack-webhook-url: 'https://hooks.slack.com/services/OUR_WORKSPACE/YOUR_APP/YOUR_TOKEN'
